CREATE TABLE IF NOT EXISTS `teleinfo` (
	`timestamp` BIGINT(10) NOT NULL DEFAULT '0',
	`rec_date` DATE NOT NULL DEFAULT '0000-00-00',
	`rec_time` TIME NOT NULL DEFAULT '00:00:00',
	`adco` VARCHAR(12) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`optarif` VARCHAR(4) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`isousc` tinyint(2) NOT NULL DEFAULT '0',
	`hchp` BIGINT(9) NOT NULL DEFAULT '0',
	`hchc` BIGINT(9) NOT NULL DEFAULT '0',
	`ptec` VARCHAR(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`inst1` tinyint(3) NOT NULL DEFAULT '0',
	`inst2` tinyint(3) NOT NULL DEFAULT '0',
	`inst3` tinyint(3) NOT NULL DEFAULT '0',
	`imax1` tinyint(3) NOT NULL DEFAULT '0',
	`imax2` tinyint(3) NOT NULL DEFAULT '0',
	`imax3` tinyint(3) NOT NULL DEFAULT '0',
	`pmax` INT(5) NOT NULL DEFAULT '0',
	`papp` INT(5) NOT NULL DEFAULT '0',
	`hhphc` VARCHAR(1) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`motdetat` VARCHAR(6) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`ppot` VARCHAR(2) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
	`adir1` tinyint(3) NOT NULL DEFAULT '0',
	`adir2` tinyint(3) NOT NULL DEFAULT '0',
	`adir3` tinyint(3) NOT NULL DEFAULT '0',
	UNIQUE KEY `timestamp` (`timestamp`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
